name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: client/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/imagetagging-client:${{ github.ref }}
            ghcr.io/imagetagging-client:latest
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            #ghcr.io/${{ github.repository_owner }}/imagetagging-server:${{ github.ref }}
            ghcr.io/${{ github.repository_owner }}/imagetagging-server:latest
          
      - name: Inspect
        run: |
          docker buildx imagetools inspect ghcr.io/notpetya1337/imagetagging-server:latest  
