name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
      runs-on: ubuntu-latest
      services:
        registry:
          image: registry:2
          ports:
            - 5000:5000

  build:

     runs-on: ubuntu-latest

     steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the server Docker image
  #     run: docker build . --file server/Dockerfile --tag imagetagging-server:$(date +%s)
  #      -
  #   - uses: actions/checkout@v3
  #   - name: Build the client Docker image
  #     run: docker build . --file client/Dockerfile --tag imagetagging-client:$(date +%s)
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: client/Dockerfile
          push: true
          tags: localhost:5000/notpetya/imagetagging-client:latest
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: localhost:5000/notpetya/imagetagging-server:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/notpetya/imagetagging-server:latest  
